<a href="https://colab.research.google.com/github/kalex066/RetailSales_DataAnalysis/blob/development/notebooks/RetailSales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Proyecto I- Parte 1 y 2 (Core)
## Análisis y Predicción de Ventas en una Tienda de Retail

### Análisis Exploratorio con Pandas

Las dos partes del proyecto las realice con Pandas en lugar de NumPy. Empezare con el analisis exploratorio utilizando pandas, que corresponde a la parte II del proyecto, y al final se encuentran los calculos adicionales que se solicitaban en la parte I con Numpy

# Carga de Datos

In [4]:
import pandas as pd
df_rs = pd.read_csv('/content/retail_sales_dataset.csv')

# Exploración Inicial de los Datos

In [5]:
# Shape
print(f"Shape: {df_rs.shape}\n")

Shape: (1000, 9)

In [6]:
# Primeras 10 filas
print(df_rs.head(10))

   Transaction ID        Date Customer ID  Gender  Age Product Category  \
0               1  2023-11-24     CUST001    Male   34           Beauty
1               2  2023-02-27     CUST002  Female   26         Clothing
2               3  2023-01-13     CUST003    Male   50      Electronics
3               4  2023-05-21     CUST004    Male   37         Clothing
4               5  2023-05-06     CUST005    Male   30           Beauty
5               6  2023-04-25     CUST006  Female   45           Beauty
6               7  2023-03-13     CUST007    Male   46         Clothing
7               8  2023-02-22     CUST008    Male   30      Electronics
8               9  2023-12-13     CUST009    Male   63      Electronics
9              10  2023-10-07     CUST010  Female   52         Clothing

   Quantity  Price per Unit  Total Amount
0         3              50           150
1         2             500          1000
2         1              30            30
3         1             500           500
4         2              50           100
5         1              30            30
6         2              25            50
7         4              25           100
8         2             300           600
9         4              50           200

In [7]:
# Tipos de datos
df_rs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

In [8]:
# Estadisticas Descriptivas
df_rs.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

In [9]:
# ultimas filas
df_rs.tail(5)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

# Inspeccion de Datos

In [10]:
# Tipos de datos
print("Tipos de datos por columna:")
print(df_rs.dtypes)

Tipos de datos por columna:
Transaction ID       int64
Date                object
Customer ID         object
Gender              object
Age                  int64
Product Category    object
Quantity             int64
Price per Unit       int64
Total Amount         int64
dtype: object

In [11]:
# Valores unicos en la columna producto
print(df_rs['Product Category'].value_counts())

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

In [12]:
# valores unicos en la columna tienda
'''El dataset no tiene columna tienda, puedo utilizar la columna de categoria para crear tiendas
asumiendo que cada categoria es una tienda, por ejemplo, si el producto es clothing es tienda de
ropa, si el producto es beuty es una tienda de belleza, y asi..'''
def tienda_por_categoria(category):
  if category == "Clothing":
    return "Clothing Store"
  elif category == "Electronics":
    return "Electronic Store"
  else:
    return "Beauty Store"

# defino la columna tienda en el dataframe
df_rs['Tienda'] = df_rs['Product Category'].apply(tienda_por_categoria)

# valores unicos
print(df_rs['Tienda'].unique())

['Beauty Store' 'Clothing Store' 'Electronic Store']

In [13]:
# Tambien podria hacerlo directamente aplicando unique a la columna Product Category
print(df_rs['Product Category'].unique())

['Beauty' 'Clothing' 'Electronics']

# Filtrado de Datos

In [14]:
# mostrar solo las filas donde las ventas sean mayores a 50.
ventas_mayores = df_rs[df_rs['Total Amount']> 50]
print(f'Hay {len(ventas_mayores)} registros de ventas mayores a 50')
ventas_mayores.head()

Hay 783 registros de ventas mayores a 50

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Tienda
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,Beauty Store
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,Clothing Store
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,Clothing Store
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,Beauty Store
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100,Electronic Store

In [15]:
# mostrar solo las filas donde el precio  sea menor a 0.5
ventas_menores = df_rs[df_rs['Price per Unit'] < 0.5 ]
print(f'Hay {len(ventas_menores)} registros de ventas menores a 0.5')
ventas_menores.head()

Hay 0 registros de ventas menores a 0.5

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount, Tienda]
Index: []

In [16]:
# Utilizando el método query(), filtra el DataFrame para mostrar las filas donde el producto sea Manzanas y las ventas sean mayores a 30.

'''El dataset no tiene productos manzana, las categorias de producto son Beauty, Clothing y
Electronics. Para practicar el filtro, buscare los Product Category Beauty con ventas > 30'''

ventas_beauty_30 = df_rs.query("`Product Category` == 'Beauty' and `Total Amount` > 30")
print(f"Hay {len(ventas_beauty_30)} registros donde la Categoria es Beauty y las ventas son mayores a 30")
ventas_beauty_30.head()

Hay 273 registros donde la Categoria es Beauty y las ventas son mayores a 30

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Tienda
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,Beauty Store
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,Beauty Store
11,12,2023-10-30,CUST012,Male,35,Beauty,3,25,75,Beauty Store
20,21,2023-01-14,CUST021,Female,50,Beauty,1,500,500,Beauty Store
24,25,2023-12-26,CUST025,Female,64,Beauty,1,50,50,Beauty Store

# Slicing de Datos

In [17]:
# Selecciona y muestra solo las columnas Producto y Ventas del DataFrame.
df1 = df_rs[['Product Category', 'Total Amount']]
df1.head()

  Product Category  Total Amount
0           Beauty           150
1         Clothing          1000
2      Electronics            30
3         Clothing           500
4           Beauty           100

In [18]:
# Utilizando loc[], selecciona y muestra las filas de la 5 a la 10 (inclusive) y las columnas Producto y Tienda.

df2 = df_rs.loc[5:10, ['Product Category', 'Total Amount']]
df2

   Product Category  Total Amount
5            Beauty            30
6          Clothing            50
7       Electronics           100
8       Electronics           600
9          Clothing           200
10         Clothing           100

In [19]:
# Utilizando iloc[], selecciona y muestra las primeras 5 filas y las primeras 3 columnas del DataFrame

df3 = df_rs.iloc[:5, :3]
df3

   Transaction ID        Date Customer ID
0               1  2023-11-24     CUST001
1               2  2023-02-27     CUST002
2               3  2023-01-13     CUST003
3               4  2023-05-21     CUST004
4               5  2023-05-06     CUST005

#En esta parte voy a codificar los requerimientos de la parte I del proyecto, con pandas

## Exploracion de Datos

In [25]:
# Calcula el total de ventas por categoría de producto
totalventas_por_categoria = df_rs.groupby('Product Category')['Total Amount'].sum()
print(totalventas_por_categoria)

Product Category
Beauty         143515
Clothing       155580
Electronics    156905
Name: Total Amount, dtype: int64

In [41]:
# Calcula el promedio de ventas diarias por categoría de producto.
ventas_diarias = df_rs.groupby(['Product Category', 'Date'])['Total Amount'].sum()
promedio_ventas_diario = ventas_diarias.groupby('Product Category').mean()
print(promedio_ventas_diario)

Product Category
Beauty         703.504902
Clothing       670.603448
Electronics    716.461187
Name: Total Amount, dtype: float64

In [26]:
# Identifica las categorías de productos con mayores y menores ventas.
mayor_y_menor_venta = df_rs.groupby('Product Category')['Total Amount'].sum().describe()
print(mayor_y_menor_venta)

'''comparando los valores con el resultado del codigo anterior (suma total por categoria) puedo ver
el resultado, pero como quiero que me aparezcan los nombres, intentare otra forma'''
categoria_mayor_venta = totalventas_por_categoria.idxmax()
maximo = totalventas_por_categoria.max()

categoria_menor_venta = totalventas_por_categoria.idxmin()
minimo = totalventas_por_categoria.min()
print(f' La categoria de producto de mayor venta es: {categoria_mayor_venta} con un valor de $ {maximo}')
print(f' La categoria de producto de menor venta es: {categoria_menor_venta} con un valor de $ {minimo}')

count         3.000000
mean     152000.000000
std        7378.029886
min      143515.000000
25%      149547.500000
50%      155580.000000
75%      156242.500000
max      156905.000000
Name: Total Amount, dtype: float64
 La categoria de producto de mayor venta es: Electronics con un valor de $ 156905
 La categoria de producto de menor venta es: Beauty con un valor de $ 143515

# Manipulacion de Datos

In [43]:
# Filtra los datos para mostrar solo las ventas de una categoría de producto especí
categoria = 'Clothing'
df_categoria = df_rs[df_rs['Product Category'] == categoria]

print(f"Las ventas de la categoria {categoria} son: \n {df_categoria['Total Amount'].head(10)}")

Las ventas de la categoria Clothing son:
 1     1000
3      500
6       50
9      200
10     100
13     120
15    1500
16     100
18      50
19     900
Name: Total Amount, dtype: int64

In [50]:
# Realiza operaciones de suma, resta, multiplicación y división en los datos para obtener estadísticas adicionales.

#sumo las ventas de una categoria especifica
total_ventas_categoria = df_categoria['Total Amount'].sum()
print(f"La suma de las ventas de la categoría {categoria} es: {total_ventas_categoria:,.2f}")

# se le aplica un descuento de 25% a una categoria especifica (aplico resta y multiplicacion)
descuento = 0.25
monto_descuento = total_ventas_categoria * descuento
ventas_con_descuento = total_ventas_categoria - monto_descuento
print(f"Las ventas de la categoria {categoria} despues de aplicarles el descuento de 25% son de {ventas_con_descuento}")

# calculo promedio de articulos por venta de una categoria especifica
unidades = df_categoria['Quantity'].sum()
numero_transacciones = len(df_categoria)
unidades_por_boleta = unidades / numero_transacciones
print(f"En la categoría {categoria}, los clientes compran en promedio {unidades_por_boleta:.1f} unidades cada vez")

La suma de las ventas de la categoría Clothing es: 155,580.00
Las ventas de la categoria Clothing despues de aplicarles el descuento de 25% son de 116685.0
En la categoría Clothing, los clientes compran en promedio 2.5 unidades cada vez